version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${SITE_PATH}:/var/www/html
    networks:
      - proxy
    restart: on-failure

  # Webservers

  backend:
    build: ./httpd
    volumes:
      - ${SITE_PATH}:/var/www/html
    networks:
      - proxy
      - backend
    restart: on-failure

  # Databases

  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
    restart: on-failure

networks:
  proxy:
  backend:

volumes:
  data:
